name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install test-specific packages
        pip install pytest pytest-cov mock
    
    - name: Install YOLOv8
      run: |
        pip install ultralytics
        wget https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt
    
    - name: Create directory structure
      run: |
        mkdir -p logs/alerts logs/benchmarks data/recordings data/detections
    
    - name: Run basic system tests
      run: |
        # These tests don't actually run detection, just test components
        python scripts/test_system.py --config config/config.json
    
    # Note: TensorRT-specific tests will not run on GitHub Actions
    # as they require NVIDIA GPU
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: logs/ 